# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\python_study\Python_Study\06_PyQt5_Eric6\01_test.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        MainWindow.setFont(font)
        MainWindow.setToolTipDuration(-1)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(90, 510, 61, 31))
        self.label.setObjectName("label")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralWidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(240, 500, 414, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_3 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.pushButton_4)
        self.pushButton_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_5 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout.addWidget(self.pushButton_5)
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_2.setGeometry(QtCore.QRect(20, 520, 151, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setLineWidth(1)
        self.label_2.setObjectName("label_2")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_6.setGeometry(QtCore.QRect(160, 510, 75, 23))
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralWidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 10, 322, 381))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.verticalLayoutWidget)
        self.textBrowser.setObjectName("textBrowser")
        self.horizontalLayout_2.addWidget(self.textBrowser)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.radioButton_ty = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_ty.setAcceptDrops(False)
        self.radioButton_ty.setChecked(True)
        self.radioButton_ty.setObjectName("radioButton_ty")
        self.horizontalLayout_3.addWidget(self.radioButton_ty)
        self.radioButton_bty = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_bty.setObjectName("radioButton_bty")
        self.horizontalLayout_3.addWidget(self.radioButton_bty)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_7 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_4.addWidget(self.pushButton_7)
        self.pushButton_8 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_4.addWidget(self.pushButton_8)
        self.pushButton_9 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_4.addWidget(self.pushButton_9)
        self.pushButton_10 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_4.addWidget(self.pushButton_10)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralWidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(360, 10, 201, 321))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.verticalLayoutWidget_2)
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.verticalLayout_2.addWidget(self.textBrowser_2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.radioButton_jb = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.radioButton_jb.setObjectName("radioButton_jb")
        self.horizontalLayout_5.addWidget(self.radioButton_jb)
        self.radioButton_bjb = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.radioButton_bjb.setChecked(True)
        self.radioButton_bjb.setObjectName("radioButton_bjb")
        self.horizontalLayout_5.addWidget(self.radioButton_bjb)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.dial = QtWidgets.QDial(self.centralWidget)
        self.dial.setGeometry(QtCore.QRect(690, 133, 50, 51))
        self.dial.setObjectName("dial")
        self.lcdNumber = QtWidgets.QLCDNumber(self.centralWidget)
        self.lcdNumber.setGeometry(QtCore.QRect(600, 50, 141, 71))
        self.lcdNumber.setObjectName("lcdNumber")
        self.horizontalSlider = QtWidgets.QSlider(self.centralWidget)
        self.horizontalSlider.setGeometry(QtCore.QRect(580, 20, 160, 22))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.verticalSlider = QtWidgets.QSlider(self.centralWidget)
        self.verticalSlider.setGeometry(QtCore.QRect(770, 20, 22, 160))
        self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider.setObjectName("verticalSlider")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralWidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(360, 350, 184, 116))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_gy = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_gy.setObjectName("pushButton_gy")
        self.gridLayout.addWidget(self.pushButton_gy, 1, 1, 1, 1)
        self.pushButton_tz = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_tz.setObjectName("pushButton_tz")
        self.gridLayout.addWidget(self.pushButton_tz, 0, 0, 1, 1)
        self.pushButton_jg = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_jg.setObjectName("pushButton_jg")
        self.gridLayout.addWidget(self.pushButton_jg, 3, 0, 1, 1)
        self.pushButton_xw = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_xw.setObjectName("pushButton_xw")
        self.gridLayout.addWidget(self.pushButton_xw, 1, 0, 1, 1)
        self.pushButton_ab = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_ab.setObjectName("pushButton_ab")
        self.gridLayout.addWidget(self.pushButton_ab, 3, 1, 1, 1)
        self.pushButton_yz = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_yz.setObjectName("pushButton_yz")
        self.gridLayout.addWidget(self.pushButton_yz, 0, 1, 1, 1)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralWidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(20, 400, 321, 80))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButton_zfc = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_zfc.setObjectName("pushButton_zfc")
        self.horizontalLayout_6.addWidget(self.pushButton_zfc)
        self.pushButton_zx = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_zx.setObjectName("pushButton_zx")
        self.horizontalLayout_6.addWidget(self.pushButton_zx)
        self.pushButton_xlk = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_xlk.setObjectName("pushButton_xlk")
        self.horizontalLayout_6.addWidget(self.pushButton_xlk)
        self.pushButton_11_zdy = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_11_zdy.setObjectName("pushButton_11_zdy")
        self.horizontalLayout_6.addWidget(self.pushButton_11_zdy)
        self.graphicsView = QtWidgets.QGraphicsView(self.centralWidget)
        self.graphicsView.setGeometry(QtCore.QRect(610, 190, 161, 141))
        self.graphicsView.setStyleSheet("border-image: url(:/picture01/src/my cat.jpg);")
        self.graphicsView.setObjectName("graphicsView")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menuBar)
        self.menu_2.setObjectName("menu_2")
        self.menuview = QtWidgets.QMenu(self.menuBar)
        self.menuview.setObjectName("menuview")
        self.menu_3 = QtWidgets.QMenu(self.menuBar)
        self.menu_3.setObjectName("menu_3")
        MainWindow.setMenuBar(self.menuBar)
        self.actionopen = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/picture01/src/open-file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionopen.setIcon(icon)
        self.actionopen.setObjectName("actionopen")
        self.actionclose = QtWidgets.QAction(MainWindow)
        self.actionclose.setObjectName("actionclose")
        self.actionsave = QtWidgets.QAction(MainWindow)
        self.actionsave.setObjectName("actionsave")
        self.actionexit = QtWidgets.QAction(MainWindow)
        self.actionexit.setObjectName("actionexit")
        self.actioncopy = QtWidgets.QAction(MainWindow)
        self.actioncopy.setObjectName("actioncopy")
        self.actioncut = QtWidgets.QAction(MainWindow)
        self.actioncut.setObjectName("actioncut")
        self.actionpaset = QtWidgets.QAction(MainWindow)
        self.actionpaset.setObjectName("actionpaset")
        self.actionmax = QtWidgets.QAction(MainWindow)
        self.actionmax.setObjectName("actionmax")
        self.actionmin = QtWidgets.QAction(MainWindow)
        self.actionmin.setObjectName("actionmin")
        self.actionabout = QtWidgets.QAction(MainWindow)
        self.actionabout.setObjectName("actionabout")
        self.actionabout_auther = QtWidgets.QAction(MainWindow)
        self.actionabout_auther.setObjectName("actionabout_auther")
        self.actionhelp = QtWidgets.QAction(MainWindow)
        self.actionhelp.setObjectName("actionhelp")
        self.actionconnect_us = QtWidgets.QAction(MainWindow)
        self.actionconnect_us.setObjectName("actionconnect_us")
        self.menu.addAction(self.actionopen)
        self.menu.addAction(self.actionclose)
        self.menu.addAction(self.actionsave)
        self.menu.addAction(self.actionexit)
        self.menu_2.addAction(self.actioncopy)
        self.menu_2.addAction(self.actioncut)
        self.menu_2.addAction(self.actionpaset)
        self.menuview.addAction(self.actionmax)
        self.menuview.addAction(self.actionmin)
        self.menu_3.addAction(self.actionabout)
        self.menu_3.addAction(self.actionabout_auther)
        self.menu_3.addAction(self.actionconnect_us)
        self.menu_3.addAction(self.actionhelp)
        self.menuBar.addAction(self.menu.menuAction())
        self.menuBar.addAction(self.menu_2.menuAction())
        self.menuBar.addAction(self.menuview.menuAction())
        self.menuBar.addAction(self.menu_3.menuAction())

        self.retranslateUi(MainWindow)
        self.pushButton_3.clicked.connect(MainWindow.showMaximized)
        self.pushButton_4.clicked.connect(MainWindow.showMinimized)
        self.pushButton_2.clicked.connect(MainWindow.showNormal)
        self.pushButton.clicked.connect(MainWindow.close)
        self.pushButton_5.clicked.connect(self.label_2.clear)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "你好"))
        self.pushButton_3.setText(_translate("MainWindow", "最大化"))
        self.pushButton_4.setText(_translate("MainWindow", "最小化"))
        self.pushButton_2.setText(_translate("MainWindow", "正常"))
        self.pushButton.setText(_translate("MainWindow", "关闭"))
        self.pushButton_5.setText(_translate("MainWindow", "清零"))
        self.label_2.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#0000ff;\">hhh</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "hello_world!"))
        self.pushButton_6.setText(_translate("MainWindow", "edit"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'楷体\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Display:</p></body></html>"))
        self.radioButton_ty.setText(_translate("MainWindow", "同意"))
        self.radioButton_bty.setText(_translate("MainWindow", "不同意"))
        self.lineEdit.setText(_translate("MainWindow", "please input:"))
        self.pushButton_7.setText(_translate("MainWindow", "清除输入"))
        self.pushButton_8.setText(_translate("MainWindow", "打印信息"))
        self.pushButton_9.setText(_translate("MainWindow", "获取"))
        self.pushButton_10.setText(_translate("MainWindow", "清除"))
        self.textBrowser_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'楷体\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">加班吗？</p></body></html>"))
        self.radioButton_jb.setText(_translate("MainWindow", "加班"))
        self.radioButton_bjb.setText(_translate("MainWindow", "不加班"))
        self.pushButton_gy.setText(_translate("MainWindow", "关于"))
        self.pushButton_tz.setText(_translate("MainWindow", "通知对话框"))
        self.pushButton_jg.setText(_translate("MainWindow", "警告对话框"))
        self.pushButton_xw.setText(_translate("MainWindow", "询问对话框"))
        self.pushButton_ab.setText(_translate("MainWindow", "AboutQt"))
        self.pushButton_yz.setText(_translate("MainWindow", "严重警告"))
        self.pushButton_zfc.setText(_translate("MainWindow", "字符串"))
        self.pushButton_zx.setText(_translate("MainWindow", "整形"))
        self.pushButton_xlk.setText(_translate("MainWindow", "下拉框"))
        self.pushButton_11_zdy.setText(_translate("MainWindow", "自定义对话框"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.menu_2.setTitle(_translate("MainWindow", "编辑"))
        self.menuview.setTitle(_translate("MainWindow", "视图"))
        self.menu_3.setTitle(_translate("MainWindow", "帮助"))
        self.actionopen.setText(_translate("MainWindow", "open"))
        self.actionclose.setText(_translate("MainWindow", "close"))
        self.actionsave.setText(_translate("MainWindow", "save"))
        self.actionexit.setText(_translate("MainWindow", "exit"))
        self.actioncopy.setText(_translate("MainWindow", "copy"))
        self.actioncut.setText(_translate("MainWindow", "cut"))
        self.actionpaset.setText(_translate("MainWindow", "paste"))
        self.actionmax.setText(_translate("MainWindow", "max"))
        self.actionmin.setText(_translate("MainWindow", "min"))
        self.actionabout.setText(_translate("MainWindow", "about"))
        self.actionabout_auther.setText(_translate("MainWindow", "about auther"))
        self.actionhelp.setText(_translate("MainWindow", "help"))
        self.actionconnect_us.setText(_translate("MainWindow", "connect us"))

import picture_src_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

